#================DOCTORS================

#Api for listing all doctors
###
GET http://127.0.0.1:8000/doctors/
Accept: application/json


#Api for adding doctor
###
POST  http://127.0.0.1:8000/doctors/
Content-Type: application/json

{
    "name":"georgemathew",
    "specialization":"urology",
    "fee":5000,
    "qualification":"mbbs",
    "email":"georgemathew@gmail.com"

}

# Api for fetching doctor detail

#api for updating doctor

# doctor delete

# doctors filter

#v2 endpoints

#Api for listing all doctors
###
GET http://127.0.0.1:8000/v2/doctors/
Accept: application/json
Authorization: Basic admin:admin

#Api for adding doctor
###
POST  http://127.0.0.1:8000/v2/doctors/
Content-Type: application/json
Authorization: Basic admin:admin

{
    "name":"tg antony",
    "specialization":"urology",
    "fee":500,
    "qualification":"mbbs",
    "email":"t@gmail.com"
   

}

#api call for fetching doctor detail
###
GET http://127.0.0.1:8000/v2/doctors/2/
Accept: application/json


#api call for update
###
PUT  http://127.0.0.1:8000/v2/doctors/2/
Content-Type: application/json

{
  "id": "2",
  "name": "sreekumar thekoot",
  "specialization": "other",
  "fee": -650,
  "qualification": "mbbs",
  "email": "kumar@gmail.com"
}


#api call for creating admin user
###
POST  http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{
    "username":"test",
    "email":"test@gmail.com",
    "password":"test@123"
}


# appointments api calls==================

#api call for list all appointments
###
GET http://127.0.0.1:8000/appointments/
Accept: application/json

#api call for book an appointment
###
POST http://127.0.0.1:8000/appointments/
Content-Type: application/json

{
    "patient_name":"hari",
    "phone":5665777,
    "doctor":2,
    "appointment_date":"2026-10-2",
    "problem":"weezing"

}