#================DOCTORS================

#Api for listing all doctors

#Api for adding doctor

# Api for fetching doctor detail

#api for updating doctor

# doctor delete

# doctors filter

#=================Appointments===========