# Generated by Django 6.1.1 on 2026-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'Ear, Nose & Throat (ENT)'), ('gastroenterology', 'Gastroenterology'), ('general_medicine', 'General Medicine / Internal Medicine'), ('general_surgery', 'General Surgery'), ('gynecology', 'Gynecology & Obstetrics'), ('hematology', 'Hematology'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('urology', 'Urology'), ('other', 'Other')], default='other', max_length=200),
        ),
    ]
